# Interface-to-NIC mapping for UPF
# Values are injected via PackageVariant apply-setters
apiVersion: v1
kind: ConfigMap
metadata:
  name: interface-setters
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  n3-interface: "eno49" # kpt-set: ${n3-interface}
  n4-interface: "eno49" # kpt-set: ${n4-interface}
  n6-interface: "eno49" # kpt-set: ${n6-interface}
