---
apiVersion: v1
kind: Service
metadata:
  name: nssf
  labels:
    app.kubernetes.io/version: "v3.1.1"
    project: sdcore5g
    nf: nssf
spec:
  type: ClusterIP
  selector:
    project: sdcore5g
    nf: nssf
  ports:
  - name: sbi
    port: 29531
    protocol: TCP