# Interface-to-NIC mapping for SMF
# Values are injected via PackageVariant apply-setters
apiVersion: v1
kind: ConfigMap
metadata:
  name: interface-setters
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  n4-interface: "eno49" # kpt-set: ${n4-interface}
