---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-arbiter-headless
  namespace: "sdcore5g"
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-13.6.4
    app.kubernetes.io/instance: sdcore5g
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: arbiter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-mongodb
      port: 27017
      targetPort: mongodb
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: sdcore5g
    app.kubernetes.io/component: arbiter
---
# Source: sd-core/charts/5g-control-plane/charts/mongodb/templates/replicaset/headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: "sdcore5g"
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-13.6.4
    app.kubernetes.io/instance: sdcore5g
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: "mongodb"
      port: 27017
      targetPort: mongodb
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: sdcore5g
    app.kubernetes.io/component: mongodb
