# Replaces the "master" field in AMF NAD's spec.config
apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: replace-nad-master-interfaces
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:

  # ── AMF: N2 interface ──────────────────────────────────────────────
  - source:
      kind: ConfigMap
      name: interface-setters
      fieldPath: data.n2-interface
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          annotations:
            specializer.nephio.org/owner: req.nephio.org/v1alpha1.Interface.n2
        fieldPaths:
          - spec.config
        options:
          delimiter: '"master":"'
          index: 1
