---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udr
  labels:
    app.kubernetes.io/version: "v3.1.1"
    project: sdcore5g
    nf: udr
spec:
  replicas: 1
  #serviceName: udr-headless
  selector:
    matchLabels:
      project: sdcore5g
      nf: udr
  template:
    metadata:
      labels:
        project: sdcore5g
        nf: udr
    spec:
      serviceAccountName: udr
      initContainers:
      - name: wait-udr-module
        image: omecproject/pod-init:1.0.0
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nslookup udr; do echo waiting for udr; sleep 4; done;']
      containers:
      - name: udr
        image: omecproject/5gc-udr:rel-1.4.0
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        command: ["/free5gc/script/udr-run.sh"]
        env:
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: "99"
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: "info"
        - name: GRPC_TRACE
          value: "all"
        - name: GRPC_VERBOSITY
          value: "debug"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MANAGED_BY_CONFIG_POD 
          value: "true"
        volumeMounts:
        - name: run-script
          mountPath: /free5gc/script/udr-run.sh
          subPath: udr-run.sh
        - name: nf-config
          mountPath: /free5gc/config
      volumes:
      - name: run-script
        configMap:
          name: udr
          defaultMode: 493
      - name: nf-config
        configMap:
          name: udr
          defaultMode: 493
