---
apiVersion: v1
kind: Service
metadata:
  name: udr
  labels:
    app.kubernetes.io/version: "v3.1.1"
    project: sdcore5g
    nf: udr
spec:
  type: ClusterIP
  selector:
    project: sdcore5g
    nf: udr
  ports:
  - name: sbi
    port: 29504
    protocol: TCP