apiVersion: v1
kind: Service
metadata:
  name: ausf
  labels:
    app.kubernetes.io/version: "v3.1.1"
    project: sdcore5g
    nf: ausf
spec:
  type: ClusterIP
  selector:
    project: sdcore5g
    nf: ausf
  ports:
  - name: sbi
    port: 29509
    protocol: TCP
