---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: "sdcore5g-cp"
  labels:
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-20.0.4
    app.kubernetes.io/instance: sdcore5g
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: kafka
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: false
  ports:
    - name: tcp-client
      port: 9092
      protocol: TCP
      targetPort: kafka-client
    - name: tcp-internal
      port: 9093
      protocol: TCP
      targetPort: kafka-internal
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: sdcore5g
    app.kubernetes.io/component: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: "sdcore5g-cp"
  labels:
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-20.0.4
    app.kubernetes.io/instance: sdcore5g
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: kafka
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-client
      port: 9092
      protocol: TCP
      targetPort: kafka-client
      nodePort: null
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: sdcore5g
    app.kubernetes.io/component: kafka