---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka
  namespace: "sdcore5g-cp"
  labels:
    app.kubernetes.io/name: kafka
    helm.sh/chart: kafka-20.0.4
    app.kubernetes.io/instance: sdcore5g
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: kafka
  annotations:
automountServiceAccountToken: true
