---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nrf
  labels:
    project: sdcore5g
    nf: nrf
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
      - patch
    resources:
      - statefulsets
      - daemonsets
      - jobs
      - pods
      - services
      - endpoints
      - configmaps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nrf
  labels:
    project: sdcore5g
    nf: nrf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nrf
subjects:
  - kind: ServiceAccount
    name: nrf
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nrf
  labels:
    project: sdcore5g
    nf: nrf
